#!/usr/bin/env bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

set -euo pipefail

die() {
  echo "ERROR: $*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "required command is unavailable: $1"
}

stage="${1:?usage: activate-nereus-publications.sh B|C|D|E}"
case "${stage}" in
  B|C|D|E) ;;
  *) die "activation is valid only for stages B, C, D, or E" ;;
esac

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
results_root="${NEREUS_RESULTS_ROOT:-${repo_root}/results}"
run_env="${NEREUS_RUN_ENV:-${results_root}/deploy/latest.env}"
[[ -r "${run_env}" ]] || die "deployment run file is not readable: ${run_env}"

# run.env is generated by deploy-nereus-stage.sh and contains shell-escaped,
# non-secret identifiers only.
# shellcheck disable=SC1090
source "${run_env}"
[[ "${STAGE}" == "${stage}" ]] \
  || die "requested stage ${stage} does not match deployed stage ${STAGE}"

release="${NEREUS_RELEASE:-${RELEASE}}"
namespace="${NEREUS_NAMESPACE:-${KUBERNETES_NAMESPACE}}"
[[ "${release}" == "${RELEASE}" ]] \
  || die "release override does not match deployment run: ${release}"
[[ "${namespace}" == "${KUBERNETES_NAMESPACE}" ]] \
  || die "namespace override does not match deployment run: ${namespace}"
wait_timeout="${NEREUS_WAIT_TIMEOUT:-20m}"
admin_timeout_seconds="${NEREUS_ADMIN_TIMEOUT_SECONDS:-600}"
[[ "${admin_timeout_seconds}" =~ ^[1-9][0-9]*$
    && "${admin_timeout_seconds}" -le 86400 ]] \
  || die "NEREUS_ADMIN_TIMEOUT_SECONDS must be between 1 and 86400"
activation_dir="${RUN_DIR}/activation"
mkdir -p "${activation_dir}"

for command_name in kubectl jq od tr; do
  require_command "${command_name}"
done
recorded_context="${KUBERNETES_CONTEXT:-}"
[[ -n "${recorded_context}" ]] \
  || die "deployment run does not record KUBERNETES_CONTEXT"
current_context="$(kubectl config current-context)"
[[ "${current_context}" == "${recorded_context}" ]] \
  || die "Kubernetes context mismatch: expected ${recorded_context}, got ${current_context}"

toolset_pod="$(kubectl -n "${namespace}" get pods \
  -l "release=${release},component=toolset" \
  -o jsonpath='{.items[0].metadata.name}')"
[[ -n "${toolset_pod}" ]] || die "toolset Pod was not found"
expected_brokers="$(kubectl -n "${namespace}" get \
  "statefulset/${release}-broker" -o jsonpath='{.spec.replicas}')"
api_base="${NEREUS_BROKER_ADMIN_URL:-http://${release}-broker:8080/admin/v2/brokers}"

api_get() {
  local path="$1"
  kubectl -n "${namespace}" exec "${toolset_pod}" -- \
    curl -fsS --max-time "${admin_timeout_seconds}" "${api_base}/${path}"
}

api_post() {
  local path="$1"
  local body="$2"
  kubectl -n "${namespace}" exec "${toolset_pod}" -- \
    curl -fsS --max-time "${admin_timeout_seconds}" \
      -H 'Content-Type: application/json' \
      -X POST \
      --data "${body}" \
      "${api_base}/${path}"
}

require_readiness() {
  local file="$1"
  jq -e \
    --argjson expected "${expected_brokers}" \
    '.brokerReadinessEpoch > 0
      and (.brokerReadinessSha256 | test("^[0-9a-f]{64}$"))
      and .persistentBrokerCount == $expected' \
    "${file}" >/dev/null \
    || die "readiness does not cover all ${expected_brokers} persistent brokers: ${file}"
}

new_run_id() {
  od -An -N20 -tx1 /dev/urandom \
    | tr -d ' \n' \
    | tr '0123456789' 'abcdefghij'
}

activate_against_readiness() {
  local publication_readiness_file="$1"
  local generation_readiness_file="$2"
  local suffix="$3"
  local readiness_epoch
  local readiness_sha
  local generation_epoch
  local prepare_file="${activation_dir}/bk-activation-prepare${suffix}.json"
  local active_file="${activation_dir}/bk-activation-active${suffix}.json"
  local backfill_file="${activation_dir}/generation-backfill${suffix}.json"
  local backfill_run_id

  readiness_epoch="$(jq -er \
    '.brokerReadinessEpoch' "${publication_readiness_file}")"
  readiness_sha="$(jq -er \
    '.brokerReadinessSha256' "${publication_readiness_file}")"
  generation_epoch="$(jq -er \
    '.brokerReadinessEpoch' "${generation_readiness_file}")"

  api_post "bookkeeper-primary-wal/activation/prepare" \
    "$(jq -cn \
      --argjson epoch "${readiness_epoch}" \
      --arg sha "${readiness_sha}" \
      --argjson timeout "${admin_timeout_seconds}" \
      '{brokerReadinessEpoch:$epoch,
        brokerReadinessSha256:$sha,
        timeoutSeconds:$timeout}')" \
    > "${prepare_file}"

  # A fresh prepare is PREPARED. If the controller was interrupted after the
  # following publications CAS, the server intentionally returns the durable
  # ACTIVE record from this idempotent prepare call. Keep going: the
  # publications request below is the authoritative retry/rebind operation and
  # must still validate the requested post-restart readiness.
  jq -e \
    --argjson epoch "${readiness_epoch}" \
    --arg sha "${readiness_sha}" \
    '(.metadataVersion >= 0)
      and (
        (.lifecycle == "PREPARED"
          and .walOnlyPublicationEnabled == false
          and .asyncPublicationEnabled == false
          and .syncPublicationEnabled == false
          and .ledgerDeletionEnabled == false
          and .brokerReadinessEpoch == $epoch
          and .brokerReadinessSha256 == $sha)
        or
        (.lifecycle == "ACTIVE"
          and .walOnlyPublicationEnabled == true
          and (.publicationActivationSha256 | test("^[0-9a-f]{64}$")))
      )' \
    "${prepare_file}" >/dev/null \
    || die "BookKeeper activation prepare did not return PREPARED or a resumable ACTIVE state"

  api_post "bookkeeper-primary-wal/activation/publications" \
    "$(jq -cn \
      --argjson epoch "${readiness_epoch}" \
      --arg sha "${readiness_sha}" \
      --argjson version "$(jq -er '.metadataVersion' "${prepare_file}")" \
      --argjson timeout "${admin_timeout_seconds}" \
      '{brokerReadinessEpoch:$epoch,
        brokerReadinessSha256:$sha,
        asyncPublicationEnabled:true,
        syncPublicationEnabled:true,
        expectedMetadataVersion:$version,
        timeoutSeconds:$timeout}')" \
    > "${active_file}"
  jq -e \
    --argjson epoch "${readiness_epoch}" \
    --arg sha "${readiness_sha}" \
    '.lifecycle == "ACTIVE"
      and .walOnlyPublicationEnabled == true
      and .asyncPublicationEnabled == true
      and .syncPublicationEnabled == true
      and .brokerReadinessEpoch == $epoch
      and .brokerReadinessSha256 == $sha
      and (.publicationActivationSha256 | test("^[0-9a-f]{64}$"))' \
    "${active_file}" >/dev/null \
    || die "BookKeeper publication activation is incomplete"

  backfill_run_id="$(new_run_id)"
  api_post "generation-protocol/registration-backfill" \
    "$(jq -cn --arg runId "${backfill_run_id}" '{runId:$runId}')" \
    > "${backfill_file}"
  jq -e \
    --arg runId "${backfill_run_id}" \
    --argjson generationEpoch "${generation_epoch}" \
    '.runId == $runId
      and .brokerReadinessEpoch == $generationEpoch
      and .failureCount == 0
      and (.coverageSha256 | test("^[0-9a-f]{64}$"))
      and (.boundedFailures | length) == 0' \
    "${backfill_file}" >/dev/null \
    || die "generation registration backfill or activation failed"
}

api_get "generation-protocol/readiness" \
  > "${activation_dir}/generation-readiness-before.json"
require_readiness "${activation_dir}/generation-readiness-before.json"

# A fresh deployment has no durable publication binding, so its first
# activation must use the generic generation readiness. On an interrupted
# retry, an existing ACTIVE record means brokers already advertise the
# BookKeeper binding and the service requires the current BookKeeper readiness
# instead. Probe the stronger authority first and fall back only when it is
# not yet available.
initial_publication_readiness_file="${activation_dir}/generation-readiness-before.json"
if api_get "bookkeeper-primary-wal/readiness" \
    > "${activation_dir}/bookkeeper-readiness-before.json" \
    2> "${activation_dir}/bookkeeper-readiness-before.error.txt"; then
  require_readiness "${activation_dir}/bookkeeper-readiness-before.json"
  initial_publication_readiness_file="${activation_dir}/bookkeeper-readiness-before.json"
else
  rm -f "${activation_dir}/bookkeeper-readiness-before.json"
fi

activate_against_readiness \
  "${initial_publication_readiness_file}" \
  "${activation_dir}/generation-readiness-before.json" \
  ""

echo "restarting Broker StatefulSet after first activation"
kubectl -n "${namespace}" rollout restart "statefulset/${release}-broker" \
  > "${activation_dir}/broker-rollout.txt"
kubectl -n "${namespace}" rollout status \
  "statefulset/${release}-broker" --timeout="${wait_timeout}" \
  >> "${activation_dir}/broker-rollout.txt"

api_get "bookkeeper-primary-wal/readiness" \
  > "${activation_dir}/readiness-after.json"
api_get "generation-protocol/readiness" \
  > "${activation_dir}/generation-readiness-after.json"
require_readiness "${activation_dir}/readiness-after.json"
require_readiness "${activation_dir}/generation-readiness-after.json"

# Rebind the durable activation to the strongest post-restart BookKeeper
# snapshot. Its domain intentionally differs from the pre-activation generic
# snapshot, so this reconciliation is mandatory rather than conditional.
activate_against_readiness \
  "${activation_dir}/readiness-after.json" \
  "${activation_dir}/generation-readiness-after.json" \
  "-reconciled"

api_get "bookkeeper-primary-wal/activation?timeoutSeconds=${admin_timeout_seconds}" \
  > "${activation_dir}/bk-activation-final.json"
jq -e \
  --slurpfile readiness "${activation_dir}/readiness-after.json" \
  '.lifecycle == "ACTIVE"
    and .walOnlyPublicationEnabled == true
    and .asyncPublicationEnabled == true
    and .syncPublicationEnabled == true
    and (.publicationActivationSha256 | test("^[0-9a-f]{64}$"))
    and .brokerReadinessEpoch == $readiness[0].brokerReadinessEpoch
    and .brokerReadinessSha256 == $readiness[0].brokerReadinessSha256' \
  "${activation_dir}/bk-activation-final.json" >/dev/null \
  || die "final BookKeeper activation is incomplete"

pulsar_admin() {
  kubectl -n "${namespace}" exec "${toolset_pod}" -- bin/pulsar-admin "$@"
}

if [[ "${stage}" == "C" || "${stage}" == "D" || "${stage}" == "E" ]]; then
  pulsar_admin topics create "${BENCHMARK_TOPIC}"
fi
pulsar_admin topics stats "${BENCHMARK_TOPIC}" \
  > "${activation_dir}/smoke-topic-stats.json"

echo "stage ${stage} publication and generation activation is complete"
echo "evidence: ${activation_dir}"
